### ISSUE TITLE
[feature] - add basic commands to the workout bot

### ISSUE THREAD

**Issue by benl95** [benl95/workout-bot#1]
## Description

When I want to use the workout bot for a workout I want to be able to use a set of commands so I can easily start tracking the progress of my current active workout.

## Tasks

-  [ ] /start command - begins interaction with the user by starting the Bodyweight Fitness recommend routine workout
-  [ ] /help command - returns a help message to the user explaining the functionality behind the workout bot and a set of commands the user can use to interact with the bot.
- [ ] /settings command - returns the bot's settings for this user and suggests command to edit these settings
