### ISSUE TITLE
[feature] - add rest interval timer

### ISSUE THREAD

**Issue by benl95** [benl95/workout-bot#6]
## Job story

When I'm performing a workout I want the bot to time the rest intervals between each set for me so I don't have to track it myself

## Tasks

- [ ] add a 90 second rest interval between each set.
- [ ] Send a message to the user that the rest interval timer is starting and prompting the user to rest.
- [ ] Send a notification to the user when the rest interval has expired and prompt the user to start the set.
